"""2단계: 수요 탐색. 월·요일·시간대, 카테고리·브랜드·상품 상위, 가격대별 비중."""
import pandas as pd, numpy as np
from paths import WORK
s = pd.read_pickle(WORK/"clean.pkl"); pd.set_option("display.width", 220)
v = s[s.event_type=="view"]; p = s[s.event_type=="purchase"]
print("[A] 월별")
g = s.groupby("month").agg(sessions=("sess","nunique"), users=("user_id","nunique"))
g["orders"] = p.groupby("month").order_id.nunique(); g["items"] = p.groupby("month").size(); g["revenue"] = p.groupby("month").price.sum().round(0)
g["purch_sessions"] = p.groupby("month").sess.nunique(); g["sess_conv_%"] = (g.purch_sessions/g.sessions*100).round(2)
g["aov"] = (g.revenue/g.orders).round(2); g["items_per_order"] = (g["items"]/g.orders).round(1); print(g.to_string())
print("\n[B] 요일 (0=월)")
d = s.groupby("dow").agg(sessions=("sess","nunique"), views=("event_type", lambda x: (x=="view").sum()))
d["orders"] = p.groupby("dow").order_id.nunique(); d["purch_sessions"] = p.groupby("dow").sess.nunique()
d["sess_conv_%"] = (d.purch_sessions/d.sessions*100).round(2); d["view_share_%"] = (d.views/d.views.sum()*100).round(1); d["order_share_%"] = (d.orders/d.orders.sum()*100).round(1); print(d.to_string())
print("\n[C] 시간대 UTC")
h = s.groupby("hour").agg(sessions=("sess","nunique"), views=("event_type", lambda x: (x=="view").sum()))
h["orders"] = p.groupby("hour").order_id.nunique(); h["purch_sessions"] = p.groupby("hour").sess.nunique()
h["view_share_%"] = (h.views/h.views.sum()*100).round(1); h["order_share_%"] = (h.orders/h.orders.sum()*100).round(1); h["sess_conv_%"] = (h.purch_sessions/h.sessions*100).round(2); print(h.to_string())
print("\n[D] category_id 상위 15 (구매 행 기준)")
tot_p = len(p); tot_v = len(v)
cat = p.groupby("category_id").agg(purch_items=("price","size"), revenue=("price","sum"), median_price=("price","median")).sort_values("purch_items", ascending=False)
cat["purch_share_%"] = (cat.purch_items/tot_p*100).round(1); cat["rev_share_%"] = (cat.revenue/p.price.sum()*100).round(1)
cat["views"] = v.groupby("category_id").size(); cat["view_share_%"] = (cat.views/tot_v*100).round(1)
print("카테고리 수", len(cat), "상위10 구매 비중 %", round(cat.purch_items.head(10).sum()/tot_p*100,1)); print(cat.head(15).round(2).to_string())
print("\n[E] brand 상위 15 (브랜드 확인 행만)")
pb = p.dropna(subset=["brand"]); vb = v.dropna(subset=["brand"])
print("브랜드 확인 구매 행 %", round(len(pb)/tot_p*100,1), "조회 행 %", round(len(vb)/tot_v*100,1))
br = pb.groupby("brand").agg(purch_items=("price","size"), revenue=("price","sum"), median_price=("price","median")).sort_values("purch_items", ascending=False)
br["purch_share_%"] = (br.purch_items/len(pb)*100).round(1); br["rev_share_%"] = (br.revenue/pb.price.sum()*100).round(1)
br["views"] = vb.groupby("brand").size(); br["view_share_%"] = (br.views/len(vb)*100).round(1)
print("브랜드 수", len(br), "상위10 비중 %", round(br.purch_items.head(10).sum()/len(pb)*100,1)); print(br.head(15).round(2).to_string())
print("\n[F] 상품 집중도")
pr = p.groupby("product_id").size().sort_values(ascending=False)
print("구매 상품 수", len(pr), "상위10 %", round(pr.head(10).sum()/tot_p*100,1), "상위100 %", round(pr.head(100).sum()/tot_p*100,1))
print("\n[G] 가격대별 비중 (열 = 이벤트 유형 내 비중, price>0)")
bins = [0,1,2,3,5,8,12,20,50,1e9]; lab = ["0-1","1-2","2-3","3-5","5-8","8-12","12-20","20-50","50+"]
sp = s[s.price>0].copy(); sp["band"] = pd.cut(sp.price, bins, labels=lab, right=False)
t = pd.crosstab(sp.band, sp.event_type, normalize="columns").mul(100).round(1)[["view","cart","remove_from_cart","purchase"]]
pp = sp[sp.event_type=="purchase"]; t["revenue_share_%"] = (pp.groupby("band", observed=True).price.sum()/pp.price.sum()*100).round(1); print(t.to_string())
ob = p.groupby("order_id").price.sum(); print("주문 금액 중앙값", round(ob.median(),2), "p75", round(ob.quantile(.75),2), "주문당 상품 중앙값", p.groupby("order_id").size().median())
